services:
  - type: web
    name: job-alert-system
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/job-alert-system-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASS
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false