# App
spring.application.name=job-alert-system
server.port=8080

## MySQL (we'll replace with Aiven values later)
#spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/jobalertdb}
#spring.datasource.username=${DATABASE_USER:root}
#spring.datasource.password=${DATABASE_PASS:royal}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


spring.datasource.url=${DATABASE_URL:jdbc:mysql://sql12.freesqldatabase.com:3306/sql12821537}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DATABASE_USER:sql12821537}
spring.datasource.password=${DATABASE_PASS:wb5AKfJBeP}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.data.redis.host=intent-louse-85112.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAUx4AAIncDE2MTI0MmI2NjU5NDQ0OTExOGUxMzNjMDFhZGFmNzdmMXAxODUxMTI
spring.data.redis.ssl.enabled=true
# JWT
jwt.secret=${JWT_SECRET:your-secret-key-make-it-long-and-secure}
jwt.expiration=86400000





#spring.application.name=job-alert-system
#server.port=8080
#
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USER}
#spring.datasource.password=${DATABASE_PASS}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.data.redis.host=${REDIS_HOST}
#spring.data.redis.port=${REDIS_PORT}
#spring.data.redis.password=${REDIS_PASSWORD}
#spring.data.redis.ssl.enabled=true
#
#jwt.secret=${JWT_SECRET}
#jwt.expiration=86400000