spring.application.name=job-alert-system
server.port=8080

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
server.tomcat.connection-timeout=60000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

app.admin.secret-key=${ADMIN_SECRET_KEY:mySecretAdminKey2026}

spring.profiles.active=local